### ISSUE TITLE
 Hello, I am also developing an open source braille display.

### ISSUE THREAD

**Issue by discapacidad5** [amarpersaud/BrailleDisplay#1]
Hello, I am also developing an open source braille display and I am stuck only in one thing and for me the most important. the communication protocol you already have defined one sves how to configure a hid rail protocol so that it is recognized by all screen readers you know how to use an existing code for debugging that allows you to connect to any screen reader

sorry if it is not very clear my request is that i speak spanish i am using google translator thanks

**Comment by amarpersaud** [comment]
Sorry, but this project is about creating display modules for individual letters/characters that are to be used in a display. It does not handle creating a full display, communicating with them, or implement a HID.
